prefixName: さくら荘その
siteName: 楠沐
favicon: /images/favicon.ico
avatar: /img/avatar/avatar.jpg
url: https://youjianan.github.io/
description: 再小的帆也能远航。
cdn: https://cdn.jsdelivr.net/gh/Youjianan/cdn@1.2

pjax: 1
mathjax: 0

notice: 一入IT深似海（/TДT)/
lazyloadImg: /img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

homePageSortType: -1
homeArticleShown: 10

bg:
  - https://cdn.jsdelivr.net/gh/Youjianan/cdn@1.2/img/cover/1.jpg.webp
  - https://cdn.jsdelivr.net/gh/Youjianan/cdn@1.2/img/cover/2.jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/30338105, title: Bilibili, desc: 博主的b站账号, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 楠沐的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}

siteBuildingTime: 02/22/2020

social:
  GitHub: {url: https://github.com/Youjianan, img: /img/social/github.png}
  qq: {url: /#, qrcode: /img/custom/qq.jpg, img: /img/social/qq.png}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  知乎: {url: https://www.zhihu.com/people/nanmu233, img: /img/social/zhihu.png}
  网易云: {url: https://music.163.com/#/playlist?id=783180708, img: /img/social/wangyiyun.png}

donate:
  alipay: /img/donate/alipay.png
  wechat: /img/donate/wechat.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 4881047811
  server: netease
  type: playlist
  fixed: true
  autoplay: true
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ